language: node_js
sudo: false
script: npm test
after_success:
- npm run coverage
- snyk auth $SNYK_TOKEN
- snyk monitor
env:
  global:
    secure: HmKOr556TKYsx0oN3qtYrFX1T3NteOQWH6YX2YXnavGj29atUT30sDNjgESgWA6yGK8k1/SksdD5eLdOwuYHgVWmPRwQ6jNqPKtMONt3KZq13Xtvw5IJl4FojLXEn93LcmKA+KAjNl8UM3E6MF+eIMkockDpoAJH4ROMHO8DbgfJXh55fiiA3gOb8w60yxJxpcwcK3YfMSrBbsMArebk+5MLJ7e71ceuuFWo6VUkq/E7DlXwoDjnllI98thaWJqpxKf5ikY9oTsbJYGHHdOJR67s3S3N2Nm25WwO2qIYEECRw96dxykOAvZQifNof1GYL87E3oVOg6RL5iCLyjmBROkpstJOi0IjqduJVg9bb7tOycul947QeM5RkN414gOD7TuaFow6ru34RTyWNEn0PY0JpR7/CY5A2ap6c8bUtVs41+4HXPAh61ZhcKNSJ0Su/7RIy6Eyo20IV5mLV25En31X+jQGmsfNJMIa/p87cs6n+hEEVlUo2qB4srhlK8YUXGXwRqujJRYxfBEjary17sY3HlKQR0KnUDOUbZPoW2QPutZB18saTOsPNzZa9tAnwn/IgG0xcuKbokBChpaluHqgj//VZxneC2oxSVMLC4Jyx2FMqmR6t3YnYp/033HibxZZHMhZA1R1RFIDBNgh3diFMx5o0yXRxw0TfnOpCpw=
notifications:
  slack:
    rooms:
      secure: l8F7oSqk1ViR5jbCu9SW69bgBX8I3PUzu/z8fD9JvQY/KkvUr3Jxs6zx46lRmu29Psd/B+7oysLETAe4VhDxESGopDDr48HYZgGAAlEfVQI9PPfw6nsvpZg++dHT1+gPYikmsERYyEXcqGq7s+rpWFZvT26togtavzmy+Tncm4U+ojREzd0OMIoi+mgvzW7K19bxTOHsqwNGllHoEpj8TNrBqKeP+n6+YC4RXGLLegteeYKzHmipE1jZYnIuu4WGUUoghzqIvQAvOsMoAmcur1t+6AUeRvD+xWx6kLkHKqmyKAJvRKFa2xDXkTjH3W9sntuYq5VGeTB2apYdqDpmHoOVRO1QhGSCZgJaqIQpVf+AEPeDMBpbJNeuOO55wi0ImEH3k52n616vd85Uo7EcAvNYfoGk4rszNgfJg1dCTGi/jqG9MttOF6X4eJ/WizLUKE4I/exV/33xXT28rBRxLysDTRC/aqA9cIyByWZvldF+jAPpCYw4ToJPL6cZqZoJGK86ji84v1azqLTn7oh3g3Wg0z4riF/PqaWbzcXjI8QBM5rAKI5E3vJ5rEZ+dkhxpMnmK66YWao9PP5muKq+h4wPteljCzaD0uV62NjLdka69EteM05UTMPEJ5uR+gd+rFxLlCFdZZ6v//UkcSx1u+4+48uz6CZze8ELc1PACRw=
